profiles:
  - profile_name: "sreelata_de"
    use_gmail: true
    location:
      city: "fremont"
      allowed_types: ["remote", "hybrid"]
    sites: ["linkedin", "google_jobs"]
    
  - profile_name: "prabir_nandi"
    use_gmail: false
    location:
      city: "fremont"
      allowed_types: ["remote", "hybrid"]
    sites: ["linkedin", "google_jobs"]

email:
  query_filter: 'subject:"job" OR subject:"opportunity"'

workflow:
  generate_cv: true
  upload_to_drive: true
